model:
- Conv2d:
    in_channels: 3
    kernel_size: !!python/tuple
    - 3
    - 3
    out_channels: 16
- BatchNorm2d:
    num_features: 16
- ReLU:
    inplace: true
- Sequential: {}
- Sequential: {}
- Sequential: {}
- AvgPool2d:
    kernel_size: 8
    stride: 8
- Linear:
    in_features: 64
    out_features: 10
